from .AddPreOrderActivity import AddPreOrderActivity
from .CalculateActivity import CalculateActivity
from .GetTestArchiveActivity import GetTestArchiveActivity
from .UpdateUserActivity import UpdateUserActivity