from .AddPreOrderActivity import AddPreOrderActivity
from .CalculateActivity import CalculateActivity
from .GetTestActionsActivity import GetTestActionsActivity
from .GetTestArchiveActivity import GetTestArchiveActivity
from .GetUserActivity import GetUserActivity
from .SendFeedbackActivity import SendFeedbackActivity
from .UpdateUserActivity import UpdateUserActivity
from .UserPaymentActivity import UserPaymentActivity